version: '3.7'

networks:
  academic_network:
    name: academic_network
    external: true

services:

  ca.he1:
    container_name: ca.he1.example.com
    extends:
      file: docker-compose-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.he1.example.com
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/he1:/etc/hyperledger/fabric-ca-server
    networks:
      - academic_network
