version: '3.7'

volumes:
  peer0.he1.example.com:

networks:
  academic_network:
    name: academic_network

services:

  # ca.he1:
  #   container_name: ca.he1.example.com
  #   extends:
  #     file: docker-compose-base.yaml
  #     service: ca-base
  #   environment:
  #     - FABRIC_CA_SERVER_CA_NAME=ca.he1.example.com
  #     - FABRIC_CA_SERVER_PORT=8054
  #     - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.he1.example.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.he1.example.com-cert.pem
  #   ports:
  #     - "8054:8054"
  #     - "18054:18054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/he1:/etc/hyperledger/fabric-ca-server
  #     - ../organizations/peerOrganizations/he1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ../organizations/peerOrganizations/he1.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   networks:
  #     - academic_network

  couchdb1:
    container_name: couchdb1
    extends:
      file: docker-compose-base.yaml
      service: couchdb-base
    ports:
      - "6984:5984"
    networks:
      - academic_network

  peer0.he1:
    container_name: peer0.he1.example.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      # Peer specific variables
      - CORE_PEER_ID=peer0.he1.example.com
      - CORE_PEER_ADDRESS=peer0.he1.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.he1.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.he1.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.he1.example.com:9051
      - CORE_PEER_LOCALMSPID=HE1MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.he1.example.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0he1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    depends_on:
      - couchdb1
    volumes:
      - ../organizations/peerOrganizations/he1.example.com/peers/peer0.he1.example.com:/etc/hyperledger/fabric
      - ../organizations/peerOrganizations/he1.example.com/peers/peer0.he1.example.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/he1.example.com/peers/peer0.he1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.he1.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - academic_network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4.9
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/config
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../configtx:/etc/hyperledger/config
    depends_on:
      - peer0.he1
    networks:
      - academic_network
